name: tools
description: Tools for marion.guide API.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  envied: ^0.3.0+3
  glob: ^2.1.2
  http: ^1.0.0
  image: ^4.0.17
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.4
  envied_generator: ^0.3.0+3
  lints: ^2.0.0
  test: ^1.21.0
